=== dougrich/tokenerator/token-api/schema/token.json
{
  "$schema": "http://json-schema.org/schema#",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "id": { "type": "string" },
    "revision": { "type": "number" },
    "created": { "type": "string" },
    "meta": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "name": { "type": "string" },
        "tags": {
          "type": "array",
          "items": { "type": "string" },
          "maxItems": 32
        },
        "description": { "type": "string" },
        "author": { "type": "string" }
      }
    },
    "parts": {
      "type": "array",
      "maxItems": 64,
      "items": {
        "type": "object",
        "additionalProperties": false,
        "required": [
          "id",
          "fill"
        ],
        "properties": {
          "id": { "type": "string" },
          "variant": { "type": "string" },
          "fill": {
            "type": "object",
            "additionalProperties": {
              "type": "string",
              "pattern": "^#(?:[0-9a-fA-F]{3}){1,2}$"
            }
          }
        }
      }
    }
  }
}

=== dougrich/tokenerator/cli/token.json
{
    "id": "fdsa",
    "revision": 0,
    "parts": [
        {
            "id": "demon-wings",
            "variant": "$",
            "fill": {
                "p0demon-wingslayer1": "#D00",
                "p1demon-wingslayer2": "#666"
            }
        },
        {
            "id": "basic-body",
            "variant": "$",
            "fill": {
                "p0basic-bodylayer1": "#D00"
            }
        }
    ],
    "meta": {
        "name": "Example",
        "tags": [],
        "description": "Neat",
        "author": "Douglas Richardson"
    },
    "created": ""
}
